replicaCount: 3

image:
  repository: blackmine57/monerod
  tag: latest
  pullPolicy: Always

resources: {}

service:
  type: ClusterIP
  port: 28081

command:
  - "monerod"
args:
  - "--testnet"
  - "--non-interactive"
  - "--confirm-external-bind"
  - "--rpc-bind-ip=0.0.0.0"
  - "--rpc-bind-port=28081"
  - "--data-dir=/monero/data"
